// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "player.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace {

const ::google::protobuf::Descriptor* Player_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Player_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_player_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  Player_descriptor_ = file->message_type(0);
  Player::default_instance_ = new Player();
  static const int Player_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Player, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Player, nick_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Player, ipaddress_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Player, position_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Player, rotation_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Player, target_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Player, text_),
  };
  Player_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Player_descriptor_,
      Player::default_instance_,
      Player_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Player, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Player, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(Player));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Player_descriptor_, Player::default_instance_);
  Player::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_player_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n\014player.proto\"w\n\006Player\022\n\n\002id\030\001 \002(\005\022\014\n\004"
    "nick\030\002 \002(\t\022\021\n\tipaddress\030\003 \001(\014\022\020\n\010positio"
    "n\030\004 \001(\014\022\020\n\010rotation\030\005 \001(\014\022\016\n\006target\030\006 \001("
    "\014\022\014\n\004text\030\007 \001(\t", 135,
  &protobuf_BuildDesc_player_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_player_2eproto {
  StaticDescriptorInitializer_player_2eproto() {
    protobuf_BuildDesc_player_2eproto();
  }
} static_descriptor_initializer_player_2eproto_;


// ===================================================================


const ::std::string Player::_default_nick_;
const ::std::string Player::_default_ipaddress_;
const ::std::string Player::_default_position_;
const ::std::string Player::_default_rotation_;
const ::std::string Player::_default_target_;
const ::std::string Player::_default_text_;
Player::Player()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    id_(0),
    nick_(const_cast< ::std::string*>(&_default_nick_)),
    ipaddress_(const_cast< ::std::string*>(&_default_ipaddress_)),
    position_(const_cast< ::std::string*>(&_default_position_)),
    rotation_(const_cast< ::std::string*>(&_default_rotation_)),
    target_(const_cast< ::std::string*>(&_default_target_)),
    text_(const_cast< ::std::string*>(&_default_text_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void Player::InitAsDefaultInstance() {}

Player::Player(const Player& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    id_(0),
    nick_(const_cast< ::std::string*>(&_default_nick_)),
    ipaddress_(const_cast< ::std::string*>(&_default_ipaddress_)),
    position_(const_cast< ::std::string*>(&_default_position_)),
    rotation_(const_cast< ::std::string*>(&_default_rotation_)),
    target_(const_cast< ::std::string*>(&_default_target_)),
    text_(const_cast< ::std::string*>(&_default_text_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Player::~Player() {
  if (nick_ != &_default_nick_) {
    delete nick_;
  }
  if (ipaddress_ != &_default_ipaddress_) {
    delete ipaddress_;
  }
  if (position_ != &_default_position_) {
    delete position_;
  }
  if (rotation_ != &_default_rotation_) {
    delete rotation_;
  }
  if (target_ != &_default_target_) {
    delete target_;
  }
  if (text_ != &_default_text_) {
    delete text_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* Player::descriptor() {
  if (Player_descriptor_ == NULL) protobuf_BuildDesc_player_2eproto();
  return Player_descriptor_;
}

const Player& Player::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_player_2eproto();
  return *default_instance_;
}

Player* Player::default_instance_ = NULL;

Player* Player::New() const {
  return new Player;
}

const ::google::protobuf::Descriptor* Player::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Player::GetReflection() const {
  if (Player_reflection_ == NULL) protobuf_BuildDesc_player_2eproto();
  return Player_reflection_;
}
